baseURL = 'https://hugo-8of.pages.dev/'
languageCode = 'cn'
title = 'Binlog'
theme = 'hugo-theme-tokiwa'
disableKinds = ['rss']

categories = ['随笔', '技术文章']
tags = ['AI', 'Java', '建站']

[params]
bannerFont = "fonts/exampleFont" 
description = """
欲买桂花同载酒，终不似，少年游。
""" 

[menu]
# Shown in the side menu.
[[menu.main]]
identifier = "post"
name = "文章"
url = "/posts/"
weight = 1
[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3


[taxonomies]
category = "categories"
series = "series"
tag = "tags"



[params.social]
bilibili = "http://example.com/"
github = "https://github.com/"
gitlab = "https://gitlab.com/"
instagram = "http://example.com/"
mail = "mailto:anon@example.com"
twitter = "https://twitter.com/"
weibo = "http://example.com/"
youtube = "https://youtube.com/"
zhihu = "http://example.com/"